### ISSUE TITLE
Support for multiple IPs

### ISSUE THREAD

**Issue by Slind14** [astutejoe/AutoKeyLight#2]
Hi Gabriel,

would you consider adding support for multiple IPs/key lights?

**Comment by astutejoe** [comment]
Sure, I'll set a reminder to add it this weekend :)

**Comment by Slind14** [comment]
Great, thank you.

**Comment by astutejoe** [comment]
@Slind14 There you friend:
https://github.com/astutejoe/AutoKeyLight/releases/tag/0.2.0

**Comment by Slind14** [comment]
Great, thank you
